Task49
meh-daniel/WeatherForecast2.0 pull request #7
Opened 2022-08-14 02:18 UTC by meh-daniel

49. подключить библиотеки
com.google.android.gms:play-services-location (для определения локации)
activity-ktx (для получения доступов)
fragment-ktx (для получения доступов)
реализовать получения доступов с помощью ActivityResultContracts.RequestMultiplePermissions для 
Manifest.permission.ACCESS_FINE_LOCATION
Manifest.permission.ACCESS_COARSE_LOCATION
В случае если доступы не получены выводить snackbar
В случае если доступы есть 
получить координаты
записать их в базу данных
сделать запрос погоды по координатам
отобразить погоду

2022-08-23 04:08 UTC, tusxxx requested changes

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +    private val locationPermissionRequest = registerForActivityResult(
.зачем полем класса, если вызывается в одном методе?

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +    private fun sendInfoAboutCurrentWeatherInFormatEmail(weatherUi: WeatherUI) {
r

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +    private fun eventFlowStartLifecycle() {
.убеди в надобности всего метода, почему не сделать всё через observe?

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    sealed class MyEvent {
r
.обязательно должен быть inner классом mainViewModel?
.в отдельный файл

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    private val _eventChanel = Channel<MyEvent>()
channel*

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    private fun sendEventErrorConnect(message: String){
r

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    fun sendEventErrorPermissions(message: String){
.зачем два метода??
.сделай один, куда прокидывать Event в параметрах можно.

2022-08-23 04:08 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +class MainViewModel(private val repository: WeatherRepository) : ViewModel() {
di

2022-08-23 04:23 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/data/WeatherRepositoryImpl.kt
> +    private fun getParamAppId() : String{
Потому что ты мне сам 20 июля сказал повыносить параметры в функции, чтоб читабельнее стало. Ну и вот с того момента это так и осталось)

2022-08-23 04:24 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/App.kt
> +        lateinit var weatherRepository: WeatherRepository
Мне Андрей сказал чисто по заданию делать таски, ничего лишнего не делая, поэтому его здесь нет, но в другой ветке проекта чисто для себя делаю этот проект на дагере

2022-08-23 04:31 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/data/db/AppDataBase.kt
> +        fun createAppDataBaseIfNotHaveInstance(
синглтон нужен ибо у нас одна ипостась базы данных может быть, и поэтому ось применения декларируется только вызовом одной функции, что можно представить как Синглтоном

2022-08-23 05:07 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/domain/model/CoordinatesOfCity.kt
> +data class CoordinatesOfCity(
Та у меня она есть в репозитории, ток в маперах сокрыта почти вся

2022-08-24 05:13 UTC, tusxxx requested changes

2022-08-24 05:13 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    private val _channel = Channel<MyEvent>()
_eventChannel

2022-08-24 05:13 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    fun sendErrorPermissions(message: String){
.один метод `sendEvent(event: Event)`

2022-08-24 05:13 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    private fun sendErrorConnect(message: String){
.убрать

2022-08-24 05:13 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    private fun getParamCity() : String{
.гетттер для константы?

2022-08-24 05:15 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/domain/WeatherRepository.kt
> +interface WeatherRepository {
.наверное, лучше два метода `getWeatherByCity()` `getWeatherByCoordinates()`

2022-08-24 07:11 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +    private fun getParamCity() : String{
А это можно принять за имитацию работы локально-изменяемых настроек пользователя, так как в рамках приложения погоды юзер зачастую меняет город. Но вообще да, лучше уберу отсюда

2022-08-25 06:15 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/domain/WeatherRepository.kt
> +interface WeatherRepository {
Понял принял, сделал без перегрузки, так как у меня Кординаты это сущность отдельная и идёт одним целым в параметры

2022-08-25 06:15 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/data/WeatherRepositoryImpl.kt
> +class WeatherRepositoryImpl(
Сделал...

2022-08-25 19:35 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/domain/model/WeatherData.kt
> +    data class weatherOfCitySW(val weatherOfCity: WeatherOfCity): WeatherData()
Названия классов с большой буквы)

2022-08-25 19:35 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +            }
.ctrl + alt + l

2022-08-25 19:35 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +                permissions.getOrDefault(Manifest.permission.ACCESS_COARSE_LOCATION, false) -> {
.метод подрефактори, читается тяжело

2022-08-25 19:35 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainViewModel.kt
> +            when(weathers){
ctrl + alt + l

2022-08-25 19:35 UTC, tusxxx commented on app/src/main/java/meh/daniel/com/weatherforecast20/AppSettings.kt
> +class AppSettings {
.Почему класс, а не object?

2022-08-27 07:44 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +            }
Та у меня android studio так и отрефакторчил код...
Тут ведь конструкция лямбды, которая по семантике похожа на if else, и поэтому тут максмимум что как можно преобразовать- это else вынести на новую строку

2022-08-27 07:53 UTC, meh-daniel commented on app/src/main/java/meh/daniel/com/weatherforecast20/AppSettings.kt
> +class AppSettings {
Посчитал что функции getParam*** было бы так красивее вызывать, ссылаясь на класс, который бы явно говорил откуда эти функции, ибо читая getParam*** вне контекста не сразу понимаешь откуда они вообще появились.

Помимо этого, обычно в appSettings хранятся ещё локальные настройки проекта, которые должны быть динамически изменяемыми, я хочу ещё с такой логикой в этом проекте поработать

2022-09-07 13:23 UTC, YanchenkOFF requested changes

2022-09-07 13:23 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +                else -> viewModel.sendEvent("not have permissions for get weather by your location")
в ресурсы

2022-09-07 13:23 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +                ) -> loadWeatherByLocation()
вызов может проходить два раза

2022-09-07 13:23 UTC, YanchenkOFF commented on app/src/main/java/meh/daniel/com/weatherforecast20/presentation/main/MainActivity.kt
> +            putExtra(Intent.EXTRA_SUBJECT, "Информация о погоде города: ${weatherUi.cityName}")
в ресурсы

2022-09-27 15:14 UTC, closed without merging